### ISSUE TITLE
Upgrade MVCMovie Project to the latest dotnet (4.7.2)

### ISSUE THREAD

**Issue by parthchopra** [dotnet/AspNetDocs#239]
# The project as is does not compile

- It is missing solution file
- I can update the project/solution to 4.7.2
- I can convert the controllers action methods to use async methods.

**Comment by Jamiemsm** [comment]
The Web Api Server is also missing a solution file.

**Comment by Rick-Anderson** [comment]
@parthchopra  @Jamiemsm  can you use the ASP.NET Core versions? They have alot of improvements.

**Comment by parthchopra** [comment]
Absolutely and we use Core in production as well, but I was wondering if you needed help with maintaining the docs for the full framework.

**Comment by Rick-Anderson** [comment]
@parthchopra  yes we do.

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
