### ISSUE TITLE
How do builders work together on the same setting?

### ISSUE THREAD

**Issue by martingbrown** [dotnet/AspNetDocs#293]
The following page talks about [configuration builders](https://docs.microsoft.com/en-us/aspnet/config-builder).

https://github.com/aspnet/AspNetDocs/blob/master/aspnet/config-builder.md

It would be helpful if it gave more details about how different builders can be combined. For example I have a password setting that is declared in the appSettings section. I want to specify this in a settings.xml file when developing locally and in a Key Vault when deployed to Azure.

I'm assuming that if I put the AzureKeyVaultConfigBuilder before the UserSecretsConfigBuilder in the `builders` section that it will read from Azure Key Valut first and if that fails use the Secrets.xml file. I'm assuming it wont crash if it can't find the Key Vault. It isn't quite clear to me from the page whether that is correct. 

Should I put the UserSecretsConfigBuilder first or second? Does the order make any difference?

**Comment by davidfowl** [comment]
Settings are applied in order (the doc doesn't seem to mention it) and it has nothing to do with failure its just the order for which settings are applied. Configuration keys that are added later overwrite earlier vaulues.

**Comment by Rick-Anderson** [comment]
@StephenMolloy can you provide a draft PR that explains order? For example, in ASP.NET Core Configuration I have

`CreateDefaultBuilder` provides default configuration for the app in the following order:

1. [ChainedConfigurationProvider](xref:Microsoft.Extensions.Configuration.ChainedConfigurationSource) :  Adds an existing `IConfiguration` as a source. In the default configuration case, adds the [host](#hvac) configuration and setting it as the first source for the _app_ configuration.
1. [appsettings.json](#appsettingsjson) using the [JSON configuration provider](#file-configuration-provider).
1. *appsettings.*`Environment`*.json* using the [JSON configuration provider](#file-configuration-provider). For example, *appsettings*.***Production***.*json* and *appsettings*.***Development***.*json*.
1. [App secrets](xref:security/app-secrets) when the app runs in the `Development` environment.
1. Environment variables using the [Environment Variables configuration provider](#evcp).
1. Command-line arguments using the [Command-line configuration provider](#command-line).


Configuration providers that are added later override previous key settings. For example, if MyKey is set in both appsettings.json and the environment, the environment value is used. Using the default configuration providers, the Command-line configuration provider overrides all other providers.

We need the equivalent of this.
