### ISSUE TITLE
Example for creating a "fake" SqlException gets runtime error

### ISSUE THREAD

**Issue by kiersche** [dotnet/AspNetDocs#331]
The file at [https://github.com/aspnet/AspNetDocs/blob/master/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/connection-resiliency-and-command-interception-with-the-entity-framework-in-an-asp-net-mvc-application/samples/sample7.cs](https://github.com/aspnet/AspNetDocs/blob/master/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/connection-resiliency-and-command-interception-with-the-entity-framework-in-an-asp-net-mvc-application/samples/sample7.cs), which is referenced by the tutorial at [https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/connection-resiliency-and-command-interception-with-the-entity-framework-in-an-asp-net-mvc-application](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/connection-resiliency-and-command-interception-with-the-entity-framework-in-an-asp-net-mvc-application), does compile, but gives me an error upon execution.

Line 42 (`var sqlErrorCtor = ...`) throws an exception that has the message "Sequence contains no elements".
I'm using ef core 2.2.6 and Microsoft.EntityFrameworkCore.SqlServer 2.2.0.
I used the code at [https://github.com/dotnet/efcore/issues/12024#issuecomment-389584810](https://github.com/dotnet/efcore/issues/12024#issuecomment-389584810) to work around the issue that `DbCommandInterceptor`s aren't available in ef core < 3.0.

I'm aware of the tutorial explicitly referring to EF 6. Still, this to me doesn't seem to be EF related but rather a problem with my SqlServer package version. Am I out of luck because creating SqlExceptions (and SqlErrors) isn't supported on the ef core side? Or is there maybe a workaround that could be added to the documentation, because it works regardless of which EF flavor is used?

**Comment by Rick-Anderson** [comment]
That tutorial doesn't use EF Core
Can you use ASP.NET Core?
