### ISSUE TITLE
Dead link in SignalR Self Host tutorial

### ISSUE THREAD

**Issue by steinmr** [dotnet/AspNetDocs#401]
# Issue description

The link "Download Completed Project" at the top of the following page is dead (it redirects to a page where the project can not be found):

https://github.com/dotnet/AspNetDocs/blob/master/aspnet/signalr/overview/deployment/tutorial-signalr-self-host.md

I have tried to find the project to fix the link, but I do not know where it is.

@bradygaster seems to own this doc

**Comment by bradygaster** [comment]
@steinmr - sorry this code sample was lost. If you've started going to SignalR core, we've got a more up-to-date set of samples for using it with background processes. Is that an option or do you need the solution to support Framework SignalR?

**Comment by steinmr** [comment]
We will probably migrate to Core soon anyways, so we can live without the sample for now. Thank you for your reply.
