### ISSUE TITLE
A link from create-an-odata-v4-endpoint.md is confusing

### ISSUE THREAD

**Issue by euyuil** [dotnet/AspNetDocs#402]
# Before you open an issue

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

The document: https://github.com/dotnet/AspNetDocs/blob/master/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-endpoint.md#query-the-entity-set

It looks like the document talks about OData v4.

Under the section **Query the entity set**, it says:

> The [EnableQuery] attribute enables clients to modify the query, by using query options such as $filter, $sort, and $page. For more information, see **Supporting OData Query Options**.

The address of the link **Supporting OData Query Options** is: https://github.com/dotnet/AspNetDocs/blob/master/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options.md

It's an article updated in 2013, and some of the query options were changed in OData v4, such as `$inlinecount`.

I think it might get improved by clarifying that the linked article is for an old version, or adding a new one for v4.

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
