### ISSUE TITLE
OWIN OAuth 2.0 Authorization Server Download the sample code link broken

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetDocs#415]
Moved from https://github.com/MicrosoftDocs/feedback/issues/2956 by @chanmmn

The page.
https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-oauth-20-authorization-server
The Download the sample code link
https://code.msdn.microsoft.com/OWIN-OAuth-20-Authorization-ba2b8783/file/114932/1/AuthorizationServer.zip

The link is broken.

**Comment by Rick-Anderson** [comment]
@Tratcher  do you have a recommendation on where we could get similar sample code for OWIN OAuth 2.0 Authorization?

**Comment by sixten** [comment]
So is the full code for this sample now lost to time? There are some holes in the article (which has now been removed by #416) that only the that broken link would have answered.

**Comment by Tratcher** [comment]
The OWIN Authorization server is outdated and not recommended for use with new projects.

**Comment by sixten** [comment]
That doesn't mean that the documentation and its accompanying example code are now without value.

**Comment by jonny123d** [comment]
I have problems with a project, and this lost code would be helpful.

**Comment by marknadig** [comment]
![image](https://user-images.githubusercontent.com/643921/132417750-988e9364-9fe0-49a0-8670-3e35b3f7faf2.png)
