### ISSUE TITLE
If async void has issues warn beforehand instead of condoning it

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetDocs#426]
Docs URL: https://docs.microsoft.com/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45
Docs source: https://github.com/dotnet/AspNetDocs/blob/master/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45.md

[RegisterAsyncTask Notes](https://docs.microsoft.com/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45#registerasynctask-notes) states that "you can also use async void page events directly".

Users still struggle to understand async code.

I think that the following would be a better presentation of the information:

## RegisterAsyncTask Notes

Methods hooked up with `RegisterAsyncTask` will run immediately after [PreRender](https://msdn.microsoft.com/library/ms178472.aspx).

If you use async void page events directly, as shown in the following code:

[!code-csharp[Main](using-asynchronous-methods-in-aspnet-45/samples/sample8.cs)]

you no longer have full control over when events execute. For example, if both an .aspx and a .Master define `Page_Load` events and one or both of them are asynchronous, the order of execution can't be guaranteed. The same indeterminate order for event handlers (such as `async void Button_Click` ) applies.

Async void event handlers are also considered completely handled for the page cycle pipeline and only use APIs like `RegisterAsyncTask` that consume methods which return a Task object should be used.

**Comment by Rick-Anderson** [comment]
That looks better. Do you want to PR this?

**Comment by paulomorgado** [comment]
Sure!

**Comment by paulomorgado** [comment]
@Rick-Anderson,

Done! #434
