### ISSUE TITLE
Missing example with control events

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetDocs#427]
Docs URL: https://docs.microsoft.com/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45
Docs source: https://github.com/dotnet/AspNetDocs/blob/master/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45.md

It is common on web pages to load information based on control events (like a button click). But this use case is missing from this doc.

**Comment by Rick-Anderson** [comment]
Sorry but this doc is in archive mode.
![image](https://user-images.githubusercontent.com/3605364/91358194-190ee400-e78e-11ea-9603-d1f503d445c8.png)

**Comment by paulomorgado** [comment]
@Rick-Anderson, this is still supported tech, right?

**Comment by Rick-Anderson** [comment]
Right, only for security bugs. Not for new content.
