### ISSUE TITLE
Bad link in the "Part 3, scaffolded Razor Pages in ASP.NET Core" section

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetDocs#459]
---
**Issue moved from MicrosoftDocs/feedback#3173**
- Please respond to @ghost.

---

_From @ghost on Thursday, October 8, 2020 12:05:53 PM_

**Describe the bug**
Clicking the link that redirects you to https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1#asynchronous-code should scroll down to the related header with the id "asynchronous-code", but it doesn't. The reason for that is, the id of the header is "asynchronous-code-1" and not "asynchronous-code".

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio#the-create-delete-details-and-edit-pages
2. Read the paragraph "Razor Pages are derived from PageModel. By convention, the PageModel-derived class is called <PageName>Model. The constructor uses dependency injection to add the RazorPagesMovieContext to the page. All the scaffolded pages follow this pattern. See Asynchronous code for more information on asynchronous programming with Entity Framework."
3. Click on "Asynchronous code"
4. The top of the new page is visible.

**Expected behavior**
The new page should scroll down to the relevant section titled "Asynchronous Code"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version  85.0.564.70

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3173**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Thursday, October 8, 2020 12:05:55 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/20255

**Comment by gewarren** [comment]
Thanks Rick! Was wondering why there was so little action in this repo.
