### ISSUE TITLE
Tutorial: Customize view for EF Database First with ASP.NET MVC app

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetDocs#542]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @FatWaterAudio.

---

_From @FatWaterAudio on Tuesday, March 9, 2021 6:47:11 PM_

the page at this link  --> https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/customizing-a-view?source=docs     does not work as described.  Adding the custom code to the Views/Students/Details.cshtml  causes the project to fail with a 400.0 IIS message.  ...basically a bad request. Once the failure occurs, there doesn't seem to be a way to recover without deleting the Views/Students folder and the StudentsController.cs file.  All prior code up to that point in the tutorial is auto-generated.      All prior code up to that point in the tutorial seems to run correctly.     

**To Reproduce**
1. Go to  this page   -->https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/  

2. follow all instructions up to this page  --> https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/customizing-a-view?source=docs

**Expected behavior**
The tutorial exercise where the error occurs is intended to show custom (not auto generated) output in the Views/Students/Details.cshtml page.  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 64 bit
 - Browser Chrome
 - Version 88.0.4324.190

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Tuesday, March 9, 2021 6:47:13 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @keziamicro.

---

_From @keziamicro on Wednesday, March 10, 2021 5:29:15 PM_

@FatWaterAudio Thank you for taking the time to let us know the article isn't working as you expected. I've reached out to the authors to let them know.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @FatWaterAudio.

---

_From @FatWaterAudio on Wednesday, March 10, 2021 5:36:34 PM_

@keziamicro thank you for your reply.   In my own continuing efforts, I was able to find a nearly identical tutorial using Razor Pages style development instead of MVC style development.  My current project is a new development effort.  Which of these two approaches should be preferred for new development?

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @keziamicro.

---

_From @keziamicro on Wednesday, March 10, 2021 5:38:29 PM_

Looping in @Rick-Anderson for the above ^

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @Rick-Anderson.

---

_From @Rick-Anderson on Wednesday, March 10, 2021 6:58:23 PM_

@keziamicro  please transfer to https://github.com/dotnet/AspNetDocs

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3544**
- Please respond to @Rick-Anderson.

---

_From @Rick-Anderson on Thursday, March 11, 2021 6:07:02 PM_

@alligreubel who can transfer this issue to https://github.com/dotnet/AspNetDocs ?

**Comment by Rick-Anderson** [comment]
@FatWaterAudio 

> Once the failure occurs, there doesn't seem to be a way to recover without deleting the Views/Students folder and the StudentsController.cs file.

You never need to delete code. I recommend debugging to see what you did wrong. I recommend you try the ASP.NET Core versions such as https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro and https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro
