### ISSUE TITLE
Source Code (Visual Studio sln file) for this page 

### ISSUE THREAD

**Issue by chanmmn** [dotnet/AspNetDocs#545]
**Help us make content visible**

I reached this page by typing "Repository Pattern C# sample".

**Describe the new topic**

When I reached this page there is no Source Code link I could find. 
Where is the Visual Studio (sln) file or (csproj) file for this link https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application?

**Comment by Rick-Anderson** [comment]
That's almost a decade old

> The Contoso University sample web application demonstrates how to create ASP.NET MVC 4 applications using the Entity Framework 5 Code First and Visual Studio 2012.
