### ISSUE TITLE
Configuration repo not responsive

### ISSUE THREAD

**Issue by Expecho** [dotnet/AspNetDocs#551]
[This doc](https://github.com/dotnet/AspNetDocs/blob/main/aspnet/config-builder.md) refers to a NuGet package / Git Repo. Since it is listened in the official docs I assume it is actively maintained. But there are numerous PR's waiting for review and I really do not how to get things in motion. Pinging the authors on GitHub does not work. Either remove it from the docs if it is not actual anymore or at least have someone review the PRs.

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/AspNetDocs/blob/main/aspnet/config-builder.md

What specifically needs an update?

**Comment by StephenMolloy** [comment]
3.0 preview1 is out. Addresses most of the issues that have been reported.
