### ISSUE TITLE
Missing Sample Code for "Getting Started with ASP.NET 4.5 Web Forms"

### ISSUE THREAD

**Issue by kevinoid** [dotnet/AspNetDocs#557]
Several pages in the [Getting Started with ASP.NET 4.5 Web Forms and Visual Studio 2017](https://docs.microsoft.com/aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms) tutorial have a [Download Wingtip Toys Sample Project (C#)](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) link, which appears to be broken.

https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409 redirects to https://code.msdn.microsoft.com/Getting-Started-with-221c01f5?cdn_id=2013-12-16-001 which now redirects to https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples which does not appear to contain the Wingtip Toys Sample Project.

A previous version of https://code.msdn.microsoft.com/Getting-Started-with-221c01f5?cdn_id=2013-12-16-001 with the sample code is available on the Wayback Machine at
https://web.archive.org/web/20170920070422/https://code.msdn.microsoft.com/Getting-Started-with-221c01f5?cdn_id=2013-12-16-001

It would be nice to add the code sample to https://docs.microsoft.com/en-us/samples/browse/.  If that's not feasible, perhaps updating the links to use the Wayback Machine would be appropriate?

Thanks,
Kevin

**Comment by Rick-Anderson** [comment]
Hey @kevinoid  we don't recommend folks starting out use Web Forms. I know Web Forms apps need to be maintained. We also don't control Wayback so we can't link to it.

**Comment by kevinoid** [comment]
Thanks @Rick-Anderson!  I understand.  Unfortunately, that also makes training new developers to maintain existing code bases more difficult.  It's also a bit weird to continue hosting the tutorial, but not the sample files for it.  Oh well.  Glad you're still hosting the tutorial text at least!

For reference, the link still appears in the following files:

    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/aspnet-error-handling.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/checkout-and-payment-with-paypal.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/create-the-project.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/create_the_data_access_layer.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/introduction-and-overview.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/membership-and-administration.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/shopping-cart.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/ui_and_navigation.md
    aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/url-routing.md

**Comment by Rick-Anderson** [comment]
> Thanks again @Rick-Anderson. For reference, I see 17 remaining:
> 
> ```
> $ grep -r LinkID=389434 aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/membership-and-administration.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/create-the-project.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/url-routing.md:[Download Wingtip Toys Sample Project (C#)](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) or [Download E-book (PDF)](https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Getting%20Started%20with%20ASP.NET%204.5%20Web%20Forms%20and%20Visual%20Studio%202013.pdf)
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/url-routing.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/aspnet-error-handling.md:[Download Wingtip Toys Sample Project (C#)](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) or [Download E-book (PDF)](https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Getting%20Started%20with%20ASP.NET%204.5%20Web%20Forms%20and%20Visual%20Studio%202013.pdf)
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/aspnet-error-handling.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/checkout-and-payment-with-paypal.md:[Download Wingtip Toys Sample Project (C#)](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) or [Download E-book (PDF)](https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Getting%20Started%20with%20ASP.NET%204.5%20Web%20Forms%20and%20Visual%20Studio%202013.pdf)
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/checkout-and-payment-with-paypal.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/ui_and_navigation.md:[Download Wingtip Toys Sample Project (C#)](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) or [Download E-book (PDF)](https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Getting%20Started%20with%20ASP.NET%204.5%20Web%20Forms%20and%20Visual%20Studio%202013.pdf)
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/ui_and_navigation.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/ui_and_navigation.md:[Getting Started with ASP.NET 4.5 Web Forms and Visual Studio 2013 - Wingtip Toys](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) (C#)
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/create_the_data_access_layer.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/introduction-and-overview.md:[Getting Started with ASP.NET 4.5 Web Forms and Visual Studio 2013 - Wingtip Toys](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) (C#) 
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/introduction-and-overview.md:For questions and comments, use the Q and A section included on the [Getting Started with ASP.NET 4.5 Web Forms and Visual Studio 2013 - Wingtip Toys](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) (C#) sample page.
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/introduction-and-overview.md:If an error occurs, the corresponding error messages could be confusing, with no good explanation on how to fix it. For help, you can check the [ASP.NET forums](https://forums.asp.net/). Another good source is the Q and A section in the [Getting Started with ASP.NET 4.5 Web Forms and Visual Studio 2013 - Wingtip Toys](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) (C#) sample page. 
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/shopping-cart.md:[Download Wingtip Toys Sample Project (C#)](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) or [Download E-book (PDF)](https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Getting%20Started%20with%20ASP.NET%204.5%20Web%20Forms%20and%20Visual%20Studio%202013.pdf)
> aspnet/web-forms/overview/getting-started/getting-started-with-aspnet-45-web-forms/shopping-cart.md:> This tutorial series will teach you the basics of building an ASP.NET Web Forms application using ASP.NET 4.5 and Microsoft Visual Studio Express 2013 for Web. A Visual Studio 2013 [project with C# source code](https://go.microsoft.com/fwlink/?LinkID=389434&clcid=0x409) is available to accompany this tutorial series.
> ```

**Comment by Rick-Anderson** [comment]
Making this repository Ready Only.
