### ISSUE TITLE
Monitoring and Telemetry could use a refresh

### ISSUE THREAD

**Issue by dcrreynolds** [dotnet/AspNetDocs#570]
Hi! The page [Monitoring and Telemetry (Building Real-World Cloud Apps with Azure)](https://docs.microsoft.com/en-us/aspnet/aspnet/overview/developing-apps-with-windows-azure/building-real-world-cloud-apps-with-windows-azure/monitoring-and-telemetry) could use a refresh. It has pics from "Windows Azure" and several dead image links. Thanks!

**Comment by Rick-Anderson** [comment]
Ya, I should probably delete that. We're not maintaining it.
