### ISSUE TITLE
Video Url in overview of katana is invalid

### ISSUE THREAD

**Issue by bruceburge** [dotnet/AspNetDocs#586]
# Issue description

The URL https://channel9.msdn.com/Shows/Web+Camps+TV/The-Katana-Project-OWIN-for-ASPNET used in the document 
https://github.com/dotnet/AspNetDocs/blob/main/aspnet/aspnet/overview/owin-and-katana/an-overview-of-project-katana.md

Is no longer valid, the content can't even be found when searching the channel 9 site, if I could get a valid URL I would have submitted this as a PR.

**Comment by Rick-Anderson** [comment]
That's ancient stuff. Take a look at https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core
