### ISSUE TITLE
Visual Studio 2022 Add New Scaffold Item 'There was an error running the selected code generator'

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetDocs#591]
In Visual Studio 2022, the following error message is sometimes generated when scaffolding a controller:

> There was an error running the selected code generator: 'The parameter searchFolders does not contain any entries
<img width="247" alt="image" src="https://user-images.githubusercontent.com/3605364/156674825-647e2d55-af1c-47e2-acfb-70854a19fb01.png">

The preceding error occurs when **.NET Framework project and item templates** have not been installed.

To enable scaffolding:

1. Run the [Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)
1. Select **Modify**
1. In the  right-side tab expand **ASP.NET and web development**
1. Check **Net Framework project and item templates**

![image](https://user-images.githubusercontent.com/3605364/156675314-3b6b958d-e01c-4a9f-af2a-abdd307eaf92.png)

**Comment by mrivasa** [comment]
That did not solve the issue. VS 2022 (Current) 17.2.2 Version 4.8.04161

**Comment by mhectorgato** [comment]
Upgraded from 17.1 to 17.2.6 and am getting this error after adding a new controller.

**Comment by Jafolayan1** [comment]
Adding "Microsoft.CodeAnalysis.CSharp.Workspaces" Package worked for me.

**Comment by Omzig** [comment]
> Microsoft.CodeAnalysis.CSharp.Workspaces

this did not help me

**Comment by mikehengetech** [comment]
Had this error:
![image](https://user-images.githubusercontent.com/97877231/193066081-321e72d9-7ec5-463d-bae3-46f6038da237.png)

and this error:
![image](https://user-images.githubusercontent.com/97877231/193066651-7300d486-24aa-4425-be9b-a53ea6e8946f.png)

Try:

Solution that worked for me:
install this: Microsoft.VisualStudio.Web.CodeGeneration.Utils v6.0.10
for ( Microsoft.VisualStudio.Web.CodeGeneration.Design v6.0.10) (version could be different v6.0.10)
just like here: https://www.youtube.com/watch?v=46mZCEHgBK4

**Comment by Ali-alshreef** [comment]
New Problem I try Old Version For Microsoft.VisualStudio.Web.CodeGeneration.Design under 6.0.10 But No Working !!
![Screenshot_3](https://user-images.githubusercontent.com/38101610/193427739-2243b582-ea71-44e0-beed-9ef9f56035ac.png)

**Comment by zrediet** [comment]
I have been struggling for a week I even tried it updating the "Microsoft.VisualStudio.Web.CodeGeneration.Design to 6.0.10" previously but when I tried it after a week or so It magically worked.

**Comment by bilaldevelop** [comment]
you try to change .net framework version project in properties > application settings. i cueerntly have the problem on .net 4.8 version . after using 4.6 version ,this problem has been resolved!

**Comment by zaferavci1** [comment]
Thanks

**Comment by dimitarbenev** [comment]
I also had to add ".NET Framework project and item templates" for scaffolding to work

**Comment by ravikumarjangid** [comment]
Thank You

**Comment by CoToMax** [comment]
> In Visual Studio 2022, the following error message is sometimes generated when scaffolding a controller:
> 
> > There was an error running the selected code generator: 'The parameter searchFolders does not contain any entries
> 
> <img alt="image" width="247" src="https://user-images.githubusercontent.com/3605364/156674825-647e2d55-af1c-47e2-acfb-70854a19fb01.png">
> 
> The preceding error occurs when **.NET Framework project and item templates** have not been installed.
> 
> To enable scaffolding:
> 
> 1. Run the [Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)
> 2. Select **Modify**
> 3. In the  right-side tab expand **ASP.NET and web development**
> 4. Check **Net Framework project and item templates**
> 
> ![image](https://user-images.githubusercontent.com/3605364/156675314-3b6b958d-e01c-4a9f-af2a-abdd307eaf92.png)

Make sure .NET Framework 4.8 development tools is installed too!
