### ISSUE TITLE
Localized Ajax / DNN

### ISSUE THREAD

**Issue by Andy9999** [dotnet/AspNetDocs#594]
Hi!

I hope this is the right place to ask my question.

I am using DNN (aka DotNetNuke) as modular CMS platform. It supports modules using Ajax and includes the Ajax components if a page is rendered having at least one module using Ajax.

My question is, do localized Ajax components exist?

The code is looking like this:
...
using (var scriptManager = new ScriptManager //RadScriptManager
{
ID = "ScriptManager",
EnableScriptGlobalization = true,
SupportsPartialRendering = true
})
...

There is a forth parameter EnableScriptLocalization being set to true by default.

This resulted in DNN requesting a file "MicrosoftAjax.de.js" which does not exist on Microsoft's CDN for Ajax.

Am I right in my assumption that a localized version does not exist and therefore EnableScriptLocalication should be set to false? Or do maybe some other variants for other languages exist? If only one version of MicrosoftAjax.js exists, a bug fix would simply consist of changing that 4th parameter.

I would be glad if someone could point me in the right direction.

Best regards,
Andy9999

**Comment by Andy9999** [comment]
I just checked the official documentation here: https://docs.microsoft.com/en-us/aspnet/ajax/cdn/cdnajax4

Near the bottom this globalization folder is mentioned:
https://ajax.aspnetcdn.com/ajax/4.0/1/globalization/

Inside of that folder you can for example find a file "fr-FR.js" file containing culture information.

Are those files loaded automatically? That would explain why no MicrosoftAjax.de.js or MicrosoftAjax.fr.js exist and why the fourth parameter "EnableScriptLocalization" should be set to false.

Sorry for asking stupid questions.

Best regards,
Andy9999

**Comment by Andy9999** [comment]
I found this posting: https://developercommunity.visualstudio.com/t/404-error-in-browser-console-if-i-set-scriptmanage/538213

It recommends to set EnableScriptLocalization to false.

However, what the heck are the files in the globalization folder doing? Like fr-FR.js for example?

Best regards,
Andy9999

**Comment by Rick-Anderson** [comment]
Hi @Andy9999 
This is not a support forum, Try StackOverflow

**Comment by Andy9999** [comment]
This is the AspNetDocs project, isn't it? There was a link somewhere (from a Microsoft.com page) that brought me here to ask CDN related questions regarding MicrosoftAjax.js.

I read here that ScriptManager would automatically include culture information, if EnableScriptLocalization is set to True (the default setting) ->https://docs.microsoft.com/en-us/archive/msdn-magazine/2008/january/globalization-support-in-asp-net-ajax-applications

I cite:
"By default, globalization support in ASP.NET AJAX is disabled. To enable it, you must set the ScriptManager's EnableScriptGlobalization property to true. This simple act includes a __cultureInfo variable in the generated runtime page, which will look like this:
```
var __cultureInfo = '{"name":"en-GB",
  "numberFormat":{ "CurrencyDecimalDigits":2, "CurrencyDecimalSeparator":".","IsReadOnly":true, 
  "CurrencyGroupSizes":[3],"NumberGroupSizes":[3], "PercentGroupSizes":[3],"CurrencyGroupSeparator":", ",
  "CurrencySymbol":"£","NaNSymbol":"NaN", "CurrencyNegativePattern":1,"NumberNegativePattern":1, 
  "PercentPositivePattern":0,"PercentNegativePattern":0, "NegativeInfinitySymbol":"-Infinity","NegativeSign":"- ...
```
"

In those [globalization\fr-FR.js](https://ajax.aspnetcdn.com/ajax/4.0/1/globalization/fr-FR.js) I do find similar information and I wonder how they should get loaded. Having EnableScriptLocalization set to True will not even load MicrosoftAjax.js anymore from the CDN.

The solution (suggested by Steve Molloy) is to set it to False. This was my initial solution to this problem as well and it seems I have no (DNN) module that relies on the culture info, so me personally I am very fine with this. I am working on this in my spare time. However, other users of the DNN CMS and the Microsoft Ajax CDN may encounter problems if their modules would expect that variable to contain info such as date formatting, currency and so on.

But if set to False and according to your documentation and if I understood it correctly, this cultureInfo variable will not be set anymore. 

But then the question is, who loads the globalization snippet then? I assume that ScriptManager alone doesn't do that.

I couldn't find any info in your documentation about that use case. :(

Best regards,
Andy9999

**Comment by Andy9999** [comment]
Anyways, even if I am a bit disappointed, I am leaving this link here for the after world: http://haacked.com/archive/2010/05/10/globalizing-mvc-validation.aspx/

In the official documentations you will find this about the globalization folder: https://docs.microsoft.com/en-us/aspnet/ajax/cdn/cdnajax4

I cite:
"Note: The globalization scripts, such as fr-FR.js, can be found in the following folder:
https://ajax.aspnetcdn.com/ajax/4.5.1/1/globalization/"

I hope no one will get haacked because of this.

Best regards,
Andy9999
