### ISSUE TITLE
Demonstration Video Link for how-do-i-get-started-with-linq-to-xml Not Valid

### ISSUE THREAD

**Issue by lyflyflxf** [dotnet/AspNetDocs#615]
The video link [Watch video (14 minutes)](https://channel9.msdn.com/Blogs/ASP-NET-Site-Videos/how-do-i-get-started-with-linq-to-xml) is not valid now in the page [how-do-i-get-started-with-linq-to-xml](https://github.com/dotnet/AspNetDocs/blob/main/aspnet/web-forms/videos/data-access/linq-videos-from-the-vb-team/how-do-i-get-started-with-linq-to-xml.md)

**Comment by Rick-Anderson** [comment]
Thanks, we're in the process of removing bad links.
