### ISSUE TITLE
No video, no sample project

### ISSUE THREAD

**Issue by MuratTopcu** [dotnet/AspNetDocs#628]
No video, no sample project, broken links 

https://github.com/dotnet/AspNetDocs/blob/e2e1e02e0d206711e80edd99c5a0a95b4a768872/aspnet/web-api/videos/getting-started/paging-and-querying.md

**Comment by Rick-Anderson** [comment]
We're working on fixing links. 
New development should use https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api
