### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by timbze** [dotnet/AspNetDocs#782]
# Issue description

The "Watch video" link in [this page](https://github.com/dotnet/AspNetDocs/blob/main/aspnet/web-api/videos/getting-started/paging-and-querying.md) goes to 404 not found page.

**Comment by Rick-Anderson** [comment]
Why are you looking at such ancient documents?

**Comment by timbze** [comment]
> Why are you looking at such ancient documents?

Result of a Google search. Maybe the page shouldn't be there anymore if it's so ancient...
