### ISSUE TITLE
Markup not rendered in the Azure Portal

### ISSUE THREAD

**Issue by chronoclast** [dotnet/AspNetDocs#815]
I didn't know where to report this bug, sorry if this is not the right place!
It's tiny and absolutely not critical, but anyway... aiming for perfection! 😄 

It applies to the **Azure Portal workflow when creating a SignalR instance**, but I suspect that it may happen with other resources because the form seems universal.

Please note that in the second tab ("Networking"), under "Connectivity method" when selecting "Private endpoint", **the markup tags are not rendered**, so it displays:

```
Select <strong>Add</strong> to create a private endpoint
``` 

![image](https://user-images.githubusercontent.com/14571485/223170229-d854dc8c-1b25-4a7c-938b-0045d590ec76.png)

Keep up the great work!!!
Cheers!
Jaime

**Comment by Rick-Anderson** [comment]
Maybe report on Azure?

**Comment by chronoclast** [comment]
> Maybe report on Azure?

Thanks, I just reported it under Azure Community Support.
Cheers!
