### ISSUE TITLE
Germanium OKR: Content review: Delete Video topics for MVC & Web Forms

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetDocs#868]
Part of the FY24 OKR related effort to archive or remove content that is no longer useful.

Content deletion Candidates: 
162 video topics under MVC and Web-Forms: Nearly all have broken video links and videos are no longer available.  Traffic to these is almost non-existent.

- All 72 Video topics including and under  https://learn.microsoft.com/en-us/aspnet/mvc/videos/ 

- All 90 topics including and under https://learn.microsoft.com/en-us/aspnet/web-forms/videos/

**Comment by Rick-Anderson** [comment]
@wadepickett  move this issue to a repo that isn't closing.
