### ISSUE TITLE
Pluralsight links not working

### ISSUE THREAD

**Issue by hassanyahya400** [dotnet/AspNetDocs#874]
All pluralsight video links on [MVC Video Training from Pluralsight](https://learn.microsoft.com/en-us/aspnet/mvc/pluralsight) are broken. The pages cannot be found on pluralsight web sites.
Examples;
- [Introduction and Prerequisites](https://pluralsight.com/training/Player?author=scott-allen&name=aspdotnet-mvc5-fundamentals-m1-introduction&mode=live&clip=0&course=aspdotnet-mvc5-fundamentals)
- [OWIN and Katana](https://pluralsight.com/training/Player?author=scott-allen&name=aspdotnet-mvc5-fundamentals-m2-katana&mode=live&clip=0&course=aspdotnet-mvc5-fundamentals)
- [Identity and Security](https://pluralsight.com/training/Player?author=scott-allen&name=aspdotnet-mvc5-fundamentals-m3-identity&mode=live&clip=0&course=aspdotnet-mvc5-fundamentals)

**Comment by hassanyahya400** [comment]
I'll like to be the one to update the doc when we get the valid links.
Thanks

**Comment by Rick-Anderson** [comment]
@hassanyahya400 we would appreciate a PR fixing those links.

**Comment by hassanyahya400** [comment]
Hi @Rick-Anderson, where can I get the valid links so I can change it and make PR?
